// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPvVfvDawqkVAozRjhLnnJ2RM2augA7vk',
    appId: '1:60439251793:web:27b43cb5a6b2dd31cda170',
    messagingSenderId: '60439251793',
    projectId: 'inotes2906',
    authDomain: 'inotes2906.firebaseapp.com',
    storageBucket: 'inotes2906.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7R19GjRg_Jk5cCBq79v7OP-Ji564W0Gk',
    appId: '1:60439251793:android:fb884e2923f9a460cda170',
    messagingSenderId: '60439251793',
    projectId: 'inotes2906',
    storageBucket: 'inotes2906.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBHlNPQ71oDXmLpy5qYq5vWXoSaxUmJbE',
    appId: '1:60439251793:ios:4d20ce525748f6d5cda170',
    messagingSenderId: '60439251793',
    projectId: 'inotes2906',
    storageBucket: 'inotes2906.appspot.com',
    iosClientId: '60439251793-ulimi62h4tc3ckucs8mdmhfm6ajcrjcn.apps.googleusercontent.com',
    iosBundleId: 'com.hello.inotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBHlNPQ71oDXmLpy5qYq5vWXoSaxUmJbE',
    appId: '1:60439251793:ios:4d20ce525748f6d5cda170',
    messagingSenderId: '60439251793',
    projectId: 'inotes2906',
    storageBucket: 'inotes2906.appspot.com',
    iosClientId: '60439251793-ulimi62h4tc3ckucs8mdmhfm6ajcrjcn.apps.googleusercontent.com',
    iosBundleId: 'com.hello.inotes',
  );
}
